default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        require_serial: true

      - id: poetry-check
        name: poetry check
        entry: poetry check --lock
        language: system
        files: ^(pyproject\.toml|poetry\.lock)$
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
